server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /seov

spring:
  profiles:
#    active: test
    active: prod


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

app:
  default-password: 123456

logging:
  file:
    name: logs/seov.log
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB