app:
  file:
    mf-Nvl: /home/seov/MF/Order_NVL/material_report.xlsx

spring:
  datasource:
    jdbc-url: jdbc:postgresql://172.17.47.31:5432/postgres?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: postgres
    password: P@sskh0nk0l4m
    driver-class-name: org.postgresql.Driver

  datasource-secondary:
    url: jdbc:sqlserver://172.17.47.178:1433;databaseName=ANDON_v2;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  datasource-third:
    jdbc-url: jdbc:postgresql://172.17.47.22:5432/sedv_db
    username: sedv
    password: shp
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: khoanguyenhlt@gmail.com
    password: hryxarmjikapeani
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true